### ISSUE TITLE
Keep getting error: INSTALL_FAILED_VERSION_DOWNGRADE

### ISSUE THREAD

**Issue by Bl4d3s** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#13]
Hello,

I want to extract the whatsapp DB on my nonrooted Oneplus 5t (Android 7.1.1 /OxygenOS) to modify it and then restore the backup. But I keep getting the error Install_failed_version_downgrade.
What I tried: Used apktool to extract the current version of Whatsapp and the Legacy version your program downloads. Then I modified the version of the legacy to match the current version (in AndroidManifest.xml). After that I repacked the Legacy APK and signed it with a certificate (otherwise I get the error that no certificates are used to sign the apk). But then I get the error that the certificate doesnt match with the certificate of the original APK.

What can I do?

**Comment by bjohas** [comment]
See https://github.com/EliteAndroidApps/WhatsApp-Key-DB-Extractor/issues/10

**Comment by bjohas** [comment]
This post https://github.com/EliteAndroidApps/WhatsApp-Key-DB-Extractor/issues/10#issuecomment-386794491 offers a workaround if you can get hold of a spare Android 6 device to extract the key.
