### ISSUE TITLE
Whatsapp Uninstalled

### ISSUE THREAD

**Issue by luciferRK** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#31]
My whatsapp got uninstalled from my phone and even the backups where not found in the extracted folder

**Comment by tcmaps** [comment]
this stopped working looong ago

**Comment by xMoAmine** [comment]
> this stopped working looong ago

Do you by any chance know what they meant when they said they would do a full back up of data @tcmaps 
like which data?
